name: ci-sql-regression-margrit-test
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      dbtag:
        description: Tag for quantsolutions/testdb image
      max_instances:
        description: Maximum number of concurrent spec files  

jobs:
  # This workflow contains a single job called "build"
  sql-regression:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout goodx repository.  Create _dump directory in this repository.
        uses: actions/checkout@v2

      - run: mkdir -p ./_dump
      - run: echo hello world > ./_dump/world.txt             
      
      - name: Checkout docker
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image: ${{ steps.settings.outputs.dbimg }}
          options: -v ${{ github.workspace }}:/_dump 
          run: |
            echo "Running Script"      
          
      - name: Upload artifacts
        timeout-minutes: 10
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: dump
          path: _dump

