# This is a basic workflow to help you get started with Actions

name: ci-sql-regression-margrit-test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      dbtag:
        description: Tag for quantsolutions/testdb image
      max_instances:
        description: Maximum number of concurrent spec files  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sql-regression:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest
    ## From Bennie: Jy kan [ self-hosted, general ] gebruik vir enige toetse wat jy doen.
    runs-on: [ self-hosted, general ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout goodx repository.  Create _dump directory in this repository.
        uses: actions/checkout@v2
        
